### ISSUE TITLE
Solidworks 2022 assembly crash

### ISSUE THREAD

**Issue by matej0barukcic** [weianweigan/DuSwToglTF#5]
When trying to export on solidworks 2022 SP 5.0 it crashes. After pressing to convert, solidworks immediately crashes

**Comment by weianweigan** [comment]
I installed solidworks 2022 in  my computer.I will test it.
> When trying to export on solidworks 2022 SP 5.0 it crashes. After pressing to convert, solidworks immediately crashes

**Comment by weianweigan** [comment]
> When trying to export on solidworks 2022 SP 5.0 it crashes. After pressing to convert, solidworks immediately crashes

Hi @matej0barukcic . I try to export a assemblydoc that opened in sw 2022. It' ok that the glb and obj file exported. 

![image](https://user-images.githubusercontent.com/25452811/232781070-d51cfb7c-3943-46b6-925c-9ad109fd9a45.png)


There is a knowing issue that some lighting component or supreesed component will cause a crash becasue it cannot be meshed. You can check it with your assembly document.

If it is also crashed, you can send me this document or upload. I will check it and debug.

**Comment by matej0barukcic** [comment]
Hi, thanks for quick feedback. Yes, the suppressed components seems to cause crash issue. 

**Is it possible to make an update so software to just ignore the suppressed and hidden components when exporting?** 

Therefore generating glb and obj export as for example like when you're exporting as STEP format. I had for example exported some model as step format while supressing and hiding components, consequently they were not shown in opened STEP format later on.

**Comment by weianweigan** [comment]
@matej0barukcic It's not very complicated to skip suppressed components. It just requires some conditional code. However, I am busy these days. Another thing is that I don't know how many people still use this add-in. SolidWorks has an official add-in (subscription required) for exporting glTF files. 
You can visit [this](https://help.solidworks.com/2019/english/SolidWorks/sldworks/t_export_using_extended_reality.htm) for more information.
If you are not a subscription user, you can tell me. I will consider updating it during my free time.
