### ISSUE TITLE
how to install this add in?

### ISSUE THREAD

**Issue by matryba** [weianweigan/DuSwToglTF#6]
@weianweigan 
 I have just join to this comunity and unfortunately I have no idea how to install it. Would you help me?
I would be very happy if you could write step by step what should I do.  I am using SW2014.
Thank you very much.

**Comment by weianweigan** [comment]
Hi! I released a installer package in github. You can download the installer from [here](https://github.com/weianweigan/DuSwToglTF/releases). Just install it as other software and restart solid works. You can find this addin in solidworks command manager. There is a export command in the top of solidworks. Then you can use it.

**Comment by matryba** [comment]
Hi!
Thank you. For basic part works fine.
For assemblies with configuration does not work.
When I added next configuration, the SW got error.


pon., 3 lip 2023, 01:25 użytkownik dududu ***@***.***>
napisał:

**Comment by weianweigan** [comment]
@matryba Could you post error message here? There is an known issue that not support suppressed or lightweight component. I don't know why configuration will effect export process.
