### ISSUE TITLE
not working with 2020 is this still being maintained?

### ISSUE THREAD

**Issue by meowcatluke** [weianweigan/DuSwToglTF#8]
not working with 2020 is this still being maintained?

**Comment by weianweigan** [comment]
@meowcatluke It should have been functional in 2020. Could you please describe the issue you're experiencing in more detail?

**Comment by meowcatluke** [comment]
The export seems to be blank. On all exports, this is with an STL with basic geometry in solidworks.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by weianweigan** [comment]
@meowcatluke It doesn't support stl feature or file.You can export stl file to gltf directly by some tools.
